{% set name = "timerizer" %}
{% set version = "0.3.3" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
  sha256: 544bd642ac1af34eaff6f71351936e0dcb5f48fb7692b74285772b5269fab56d

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
  skip: {{ win }}

requirements:
  host:
    - ruby
  run:
    - ruby

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple set of Rails-like time helpers

  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/kylewlacy/{{ name }}

extra:
  recipe-maintainers:
    - sodre
