travis:
  secure:
    BINSTAR_TOKEN: G0B2qGzRJ/9EI4JUHB0NGPKEngYZgfuyU5jub7C1KhNd41cPdF1MqxUfDb/ZgOmEbt4J0EQ+hScnS7Wn8lRAYP5nRD9MwZM1Om7qx6Gm2I2wiep5qpHB5XR9IWhLO1gD1XGT2OmJyar6xnLyQ8t/JE7cVFKfkcYXoGo2iL9g5E+PLMPEZdGDrS82oDJJVhSqvHIUgUYvH1IFjmDmb31VPP5QgvEpO8w9VeBXMDw58vg00DLazfUtbY6LvLkqhhYSqCKKkHN4P3VvK6rGHVfzOZUek6hcPSRKNkJV4SfipYN/4JEpVQYTqtkULBrYPB2aV9q8+CYHYQOsUakrxyFoPwLUNNi7B43MjAumm+doMDYBHFLycVbr2uVkvVSLBCjY0xASbreYKRRblWg4p9JtI4BFQswCP76Jauv7DDjM0XB4Pn5ztt/tpT1yWqZvx5dnKazs63xa5PbKIwCkYbxbiN2qUjFFbIqlTznay29kBVIUWy9BHvGAXoYbb8kKp/haRNTwr2GHOyAGPmKxCv5dPW4dHzxZZcNkNTNw6trbDo7Vnon/v0UvEtl16DI4kUqAmgaWFzWikEFLOrpCLLHnxI7pFbXtKTP/+4BA0Ji5XdpeOyEY30Aa8U4THnoglAavYzjNAtvETrcm10uroUS1YsAawFNZivyLS8OaZat21AE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
